### ISSUE TITLE
Highlight all inlining adjectives

### ISSUE THREAD

**Issue by cgay** [dylan-lang/vscode-dylan#11]
By inspection of the regular expressions I see that we don't match `may-inline`, `default-inline`, or `not-inline`.

**Comment by pedro-w** [comment]
Would this be solved by using Emacs symbol matching, which we discussed a little here
https://gitter.im/dylan-lang/general?at=5fc4b5570219b46a266a4c6f
I _think_ it's possible to tell Emacs, via syntax tables, what characters can form an identifier, so it would view `may-inline` as one unit and not '`may`' '`-`' '`inline`'.

**Comment by cgay** [comment]
https://github.com/dylan-lang/dylan-mode/commit/f9d40d7db7fed5be761462a35cb6ebcb35bbb51e fixed this for emacs but this bug is for VSCode. :-)

It seems like the syntax table https://github.com/dylan-lang/dylan-mode/blob/master/dylan-mode.el#L1334 affects some basic commands like `M-b` vs `C-M-b` and TBH I'm not expert enough at elisp (yet?) to know how to best leverage it for dylan-mode.
